### PR TITLE
Issue #14 : first attempt to make the index file look better

### PR DESCRIPTION
**Pull request by mricaud**
Hi

I tried to fix issue #14 but, i didn't manage to build the project, so I'm really not sure of what I've done ... this is blind coding, sorry for that.

Regards
Matthieu

### CODE REVIEW

**Comment by cmarchand** [comment]
I do agree with you, this piece of code **must** be rewritten, but it has not a high priority level !
Let me review your code, and I tell you...

**Comment by cmarchand** [comment]
Solved in commit #3ddea9f

**Comment by cmarchand** [comment]
Solved in 1.5.1-RC7

**Comment by mricaud** [comment]
Hi Christophe, 
It looks to be quite nice on 1.5.1-RC7 but the latest version 2.0.0-RC3, the Xspec CSS seems not to be applied anymore. It's not a big deal but why not keeping this ?
Let me know if I can help.
Cheers

**Comment by cmarchand** [comment]
Solved in [issue_12](https://github.com/xspec/xspec-maven-plugin-1/tree/issue_12) branch, but won't be available quickly, due to dependances on next xspec implementaton release.

You can follow xspec implementation progress [here](https://github.com/xspec/xspec/projects/2).

**Pull request merged**
